
# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/church_app
spring.datasource.username=postgres
spring.datasource.password=Vector*1234

# JWT
jwt.secret=supersecretkeysupersecretkey123456

# Mailjet
mailjet.api.key=5e1e5b8572d3fb8b01ce7b0a897617c7
mailjet.api.secret=710029f51f303d2970adeaa86f79f0d4

# VAPID
vapid.public.key=BAYWdtlQk4egDKNrH7rUBkBkYD1jrerVb72v4wX9VHa3Vo273Q2kV2EH-G4aA_nBXBx1JgG-P2KltUqU0y0jPMI
vapid.private.key=8md7tWtsK4zur1YJHEp5wucAWc0iV-eIgtre0MUnNDY
vapid.subject=mailto:nanakwekuhwedie461@gmail.com