spring.application.name=church-backend

# JWT Configuration
jwt.secret=${JWT_SECRET:supersecretkeysupersecretkey123456}
jwt.expiration=86400000

# PostgreSQL connection
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/church_app}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Vector*1234}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Mailjet
mailjet.api.key=${MAILJET_API_KEY:5e1e5b8572d3fb8b01ce7b0a897617c7}
spring.mailjet.api.secret=${MAILJET_API_SECRET:487f5b1c86d8d696df4980395552a404}

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false

spring.profiles.include=local